### ISSUE TITLE
运行exportOnnx.py报错

### ISSUE THREAD

**Issue by studyboysong** [GesilaA/deepsort_tensorrt#16]
Traceback (most recent call last):
  File "/home/lz/software/pycharm-community-2023.2.5/plugins/python-ce/helpers/pydev/pydevd.py", line 1500, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/lz/software/pycharm-community-2023.2.5/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/lz/code/yolov5_deepsort_rt_nx-master/yolodeep2rt/deep_sort_pytorch/exportOnnx.py", line 26, in <module>
    model = build_tracker(cfg, use_cuda=False)
  File "/home/lz/code/yolov5_deepsort_rt_nx-master/yolodeep2rt/deep_sort_pytorch/deep_sort/__init__.py", line 8, in build_tracker
    if cfg.USE_FASTREID:
AttributeError: 'YamlParser' object has no attribute 'USE_FASTREID'
python-BaseException

请问一下这个怎么解决呢？

**Comment by ljl02521** [comment]
将build_tracker修改为return DeepSort(model_path=cfg.DEEPSORT.REID_CKPT,
                    max_dist=cfg.DEEPSORT.MAX_DIST, min_confidence=cfg.DEEPSORT.MIN_CONFIDENCE,
                    nms_max_overlap=cfg.DEEPSORT.NMS_MAX_OVERLAP, max_iou_distance=cfg.DEEPSORT.MAX_IOU_DISTANCE,
                    max_age=cfg.DEEPSORT.MAX_AGE, n_init=cfg.DEEPSORT.N_INIT, nn_budget=cfg.DEEPSORT.NN_BUDGET,
                    use_cuda=use_cuda)就可以了
